Target[nw_dump1090_aircraft]: `bash /etc/mrtg/dump1090-plane-count.sh`
Title[nw_dump1090_aircraft]: NW antenna aircraft seen
MaxBytes[nw_dump1090_aircraft]: 500
Options[nw_dump1090_aircraft]: integer,nopercent,growright,unknaszero,nopercent,gauge,noinfo,nobanner,withzeroes
YLegend[nw_dump1090_aircraft]: aircraft
ShortLegend[nw_dump1090_aircraft]:
LegendI[nw_dump1090_aircraft]: valid aircraft with positions seen: &nbsp;
LegendO[nw_dump1090_aircraft]: invalid aircraft without positions seen: &nbsp;
kMG[nw_dump1090_aircraft]: ,
PageTop[nw_dump1090_aircraft]: <H1>NW antenna aircraft seen</H1>




